server:
  port: 1023


spring:
  application:
    name: springboot-redis-message
  # redis  配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 500ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms

