


spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        min-idle: 20
        max-idle: 50
        max-active: 50
        max-wait: -1ms
    sentinel:
      master:
      nodes: