
#特殊处理404异常。
#SpringBoot默认不会抛出404异常<NoHandlerFoundException>。所以在ControllerAdvice中捕获不到该异常，
#导致404总是跳过该异常，直接显示EorrorController的错误页面。通过下面的配置让404抛出异常，然后由统一异常处理

# 注意：添加了如上配置会造成项目静态资源访问异常，所以一般在RESTFUL项目中，可以这样配置
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false