server:
  port: 8809
  servlet:
    context-path: /springboot-redis

spring:
  application:
    name: springboot-redis
  redis:
    host: localhost
    port: 6379
    database: 0         # 数据库
    password:
    # 注意 如果加入连接池配置，需要导入 依赖
    #<dependency>
    #    <groupId>org.apache.commons</groupId>
    #    <artifactId>commons-pool2</artifactId>
    #</dependency>
    timeout: 2000ms     # 超时时间 毫秒
    lettuce:
      pool:
        max-wait: -1ms  # 连接池的最大阻塞时间(-1 负值表示没有限制)
        max-active: 200 # 连接池最大连接数 (负值表示没有限制)
        max-idle: 10    # 连接池的最大空闲数
        min-idle: 0     # 连接池的最小空闲数

  # 多Redis配置: 依赖多个不同的redis，也就是说需要从多个redis实例中获取数据，这种时候需要我们自己来声明
  # ConnectionFactory 和 RedisTemplate
  local-redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 16
        max-wait: 100
        max-idle: 8
        min-idle: 4



